apiVersion: v1
kind: Secret
metadata:
  name: __PROJECT__-__ENVIRONMENT__-agentcore-credentials
  namespace: __DP_NAMESPACE__
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: __AWS_ACCESS_KEY_ID__
  AWS_SECRET_ACCESS_KEY: __AWS_SECRET_ACCESS_KEY__
